apiVersion: apps/v1
kind: Deployment
metadata:
  name: bokehweb
spec:
  selector:
    matchLabels:
      app: bokehweb
  replicas: 3
  template: # template for the pods
    metadata:
      labels:
        app: bokehweb
    spec:
      containers:
      - name: bokeh
<<<<<<< HEAD
        image: gcr.io/translatenav/github.com/radbrt/bokeh_cicd:latest
=======
        image: gcr.io/$PROJECT_ID/github.com/radbrt/bokeh_cicd:latest
>>>>>>> 3cf0201bdddd0cff0142246cab4de57a31b018c8
        imagePullPolicy: "Always"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5

---
kind: Service
apiVersion: v1
metadata:
  name: bokehnet
spec:
  selector:
    app: bokehweb
  ports:
    - name: bokehport
      port: 80
  type: LoadBalancer